language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="re-nfa:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="re-nfa" OCAML_VERSION="4.02.3"
  - PACKAGE="re-nfa" OCAML_VERSION="4.07.1"
